---
version: '3.7'
services:
  puppetboard:
    image: ${PUPPETB_IMAGE:-puppetboard:latest}
    hostname: puppetboard
    depends_on:
      - puppetdb
      - puppetserver
    ports:
      - 80:80
    environment:
      - PUPPETDB_HOST=puppetdb
      - PUPPETDB_SSL_VERIFY=/etc/puppetlabs/puppet/ssl/certs/ca.pem
      - PUPPETDB_KEY=/etc/puppetlabs/puppet/ssl/private_keys/private.pem
      - PUPPETDB_CERT=/etc/puppetlabs/puppet/ssl/certs/public.pem
      - INVENTORY_FACTS='Hostname,fqdn, IP Address,ipaddress'
      - ENABLE_CATALOG=True
      - GRAPH_FACTS='architecture,puppetversion,osfamily'
    volumes:
      - ./puppetserver-ca:/etc/puppetlabs/puppet/
